-- =========================================================
-- EXTENSIONS (PostgreSQL & PostGIS)
-- =========================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

-- =========================================================
-- ENUM TYPES
-- =========================================================
CREATE TYPE user_status AS ENUM ('active', 'locked');
CREATE TYPE membership_role AS ENUM ('admin', 'employee');
CREATE TYPE employee_status AS ENUM ('active', 'locked');
CREATE TYPE gender_type AS ENUM ('male', 'female', 'other');
CREATE TYPE device_platform AS ENUM ('ios', 'android');
CREATE TYPE device_status AS ENUM ('pending', 'approved', 'rejected', 'revoked');
CREATE TYPE login_request_type AS ENUM ('new_login', 'new_device');
CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE wifi_match_mode AS ENUM ('ssid', 'ssid_bssid');
CREATE TYPE attendance_method AS ENUM ('gps', 'wifi', 'gps_wifi');
CREATE TYPE shift_assignment_scope AS ENUM ('company', 'branch', 'department', 'employee');
CREATE TYPE punch_type AS ENUM ('in', 'out');
CREATE TYPE attendance_source AS ENUM ('online', 'offline', 'admin_edit');
CREATE TYPE work_status AS ENUM ('normal', 'late', 'early', 'late_early', 'forgot', 'absent');

-- =========================================================
-- FUNCTION & TRIGGER ĐỂ TỰ ĐỘNG CẬP NHẬT updated_at
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- FUNCTION & TRIGGER ĐỂ TỰ ĐỘNG ĐỒNG BỘ GEOGRAPHY POINT (POSTGIS)
-- =========================================================
CREATE OR REPLACE FUNCTION set_geography_point()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.lat IS NOT NULL AND NEW.lng IS NOT NULL THEN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.lng, NEW.lat), 4326)::geography;
  ELSE
    NEW.geom = NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 1. USERS (Tài khoản Đăng nhập Hệ thống)
-- =========================================================
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(190) UNIQUE,
  password_hash VARCHAR(255),
  is_hunonic BOOLEAN NOT NULL DEFAULT FALSE,
  status user_status NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 2. COMPANIES (Công ty)
-- =========================================================
CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  code VARCHAR(60) NOT NULL,
  timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_companies_updated_at BEFORE UPDATE ON companies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 3. BRANCHES (Chi nhánh)
-- =========================================================
CREATE TABLE branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  address VARCHAR(255),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_branches_updated_at BEFORE UPDATE ON branches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 4. DEPARTMENTS (Phòng ban — có thể thuộc chi nhánh hoặc cấp công ty)
-- =========================================================
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT REFERENCES branches(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 5. EMPLOYEES (Hồ sơ Nhân viên từng Công ty)
-- =========================================================
CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  department_id BIGINT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
  employee_code VARCHAR(60) NOT NULL,
  full_name VARCHAR(190) NOT NULL,
  birthday DATE,
  gender gender_type,
  title VARCHAR(120),
  status employee_status NOT NULL DEFAULT 'active',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_employee_user_company UNIQUE (id, user_id, company_id)
);

CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 6. COMPANY MEMBERSHIPS (Quyền của User trong từng Công ty)
-- =========================================================
CREATE TABLE company_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT,
  role membership_role NOT NULL DEFAULT 'employee',
  active_department_id BIGINT REFERENCES departments(id) ON DELETE SET NULL,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_membership_employee_user_company FOREIGN KEY (employee_id, user_id, company_id) REFERENCES employees(id, user_id, company_id) ON DELETE CASCADE,
  CONSTRAINT chk_membership_employee_required CHECK (role = 'admin' OR employee_id IS NOT NULL)
);

CREATE TRIGGER trg_company_memberships_updated_at BEFORE UPDATE ON company_memberships
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 7. DEVICES (Thiết bị đăng ký chấm công)
-- =========================================================
CREATE TABLE devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_uid VARCHAR(190) NOT NULL,
  device_name VARCHAR(190),
  platform device_platform NOT NULL,
  os_version VARCHAR(60),
  app_version VARCHAR(60),
  push_token VARCHAR(255),
  status device_status NOT NULL DEFAULT 'pending',
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_user_device UNIQUE (user_id, device_uid)
);

CREATE TRIGGER trg_devices_updated_at BEFORE UPDATE ON devices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 8. TOKENS (Quản lý Phiên đăng nhập & Token xác thực)
-- =========================================================
CREATE TABLE tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id BIGINT REFERENCES devices(id) ON DELETE SET NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  ip_address VARCHAR(60),
  user_agent VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_tokens_updated_at BEFORE UPDATE ON tokens
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 9. LOGIN APPROVAL REQUESTS (Yêu cầu duyệt thiết bị/đăng nhập)
-- =========================================================
CREATE TABLE login_approval_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
  device_id BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  request_type login_request_type NOT NULL,
  status approval_status NOT NULL DEFAULT 'pending',
  ip_address VARCHAR(60),
  user_agent VARCHAR(255),
  reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_login_approval_requests_updated_at BEFORE UPDATE ON login_approval_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 10. LOCATIONS (Danh mục Vị trí GPS Văn phòng)
-- =========================================================
CREATE TABLE locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  address VARCHAR(255),
  lat NUMERIC(10,7) NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(10,7) NOT NULL CHECK (lng BETWEEN -180 AND 180),
  radius_m INTEGER NOT NULL DEFAULT 80 CHECK (radius_m > 0),
  geom geography(Point, 4326),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_locations_updated_at BEFORE UPDATE ON locations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_locations_geom BEFORE INSERT OR UPDATE OF lat, lng ON locations
FOR EACH ROW EXECUTE FUNCTION set_geography_point();

-- =========================================================
-- 11. LOCATION EMPLOYEE OVERRIDES (Vị trí đặc cách riêng cho nhân viên)
-- =========================================================
CREATE TABLE location_employee_overrides (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_location_employee UNIQUE (location_id, employee_id)
);

-- =========================================================
-- 12. WIFIS (Danh mục Wifi được phép chấm công)
-- =========================================================
CREATE TABLE wifis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT, -- Wifi thuộc chi nhánh nào
  name VARCHAR(190),
  ssid VARCHAR(190) NOT NULL,
  bssid VARCHAR(60),
  match_mode wifi_match_mode NOT NULL DEFAULT 'ssid_bssid',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_wifi_bssid_required CHECK (match_mode = 'ssid' OR bssid IS NOT NULL)
);

CREATE TRIGGER trg_wifis_updated_at BEFORE UPDATE ON wifis
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 15. SHIFTS (Cấu hình Ca làm)
-- =========================================================
CREATE TABLE shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  start_time INTERVAL NOT NULL, -- Độ lệch giờ bắt đầu ca kể từ 00:00 ngày công (ví dụ: '08:00:00' hoặc '22:00:00')
  end_time INTERVAL NOT NULL,   -- Độ lệch giờ kết thúc ca kể từ 00:00 ngày công (ví dụ: '17:00:00' hoặc '30:00:00' cho ca đêm)
  checkin_from INTERVAL NOT NULL,
  checkin_to INTERVAL NOT NULL,
  checkout_from INTERVAL NOT NULL,
  checkout_to INTERVAL NOT NULL,
  weekdays SMALLINT NOT NULL CHECK (weekdays BETWEEN 1 AND 127), -- Bitmask: Mon=1, Tue=2, Wed=4, Thu=8, Fri=16, Sat=32, Sun=64. VD: T2-T6 = 31
  attendance_method attendance_method NOT NULL,
  late_threshold_min INTEGER NOT NULL DEFAULT 0 CHECK (late_threshold_min >= 0),
  early_threshold_min INTEGER NOT NULL DEFAULT 0 CHECK (early_threshold_min >= 0),
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 1.00 CHECK (work_credit >= 0), -- Hệ số công trực tiếp (ví dụ: 1.00 công, 0.50 công)
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_shifts_updated_at BEFORE UPDATE ON shifts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 16. SHIFT ASSIGNMENTS (Gán ca cho Nhân viên/Phòng ban/Chi nhánh)
-- =========================================================
CREATE TABLE shift_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id BIGINT NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
  scope_type shift_assignment_scope NOT NULL,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT REFERENCES branches(id) ON DELETE CASCADE,
  department_id BIGINT REFERENCES departments(id) ON DELETE CASCADE,
  employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
  starts_on DATE,
  ends_on DATE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_shift_assignment_scope CHECK (
    (scope_type = 'company'    AND branch_id IS NULL AND department_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 'branch'     AND branch_id IS NOT NULL AND department_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 'department' AND department_id IS NOT NULL AND employee_id IS NULL)
    OR
    (scope_type = 'employee'   AND employee_id IS NOT NULL AND branch_id IS NULL AND department_id IS NULL)
  ),
  CONSTRAINT chk_shift_assignment_date_range CHECK (
    ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on
  )
);

CREATE TRIGGER trg_shift_assignments_updated_at BEFORE UPDATE ON shift_assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Partial unique indexes chống gán trùng ca cho cùng đối tượng (chỉ check bản ghi active)
CREATE UNIQUE INDEX uq_shift_assign_company
  ON shift_assignments(shift_id, company_id)
  WHERE scope_type = 'company' AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_shift_assign_branch
  ON shift_assignments(shift_id, branch_id)
  WHERE scope_type = 'branch' AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_shift_assign_department
  ON shift_assignments(shift_id, department_id)
  WHERE scope_type = 'department' AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_shift_assign_employee
  ON shift_assignments(shift_id, employee_id)
  WHERE scope_type = 'employee' AND deleted_at IS NULL;

-- =========================================================
-- 17. ATTENDANCE RECORDS (Bảng ghi công tổng hợp theo ngày-nhân viên-ca)
-- =========================================================
CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL REFERENCES branches(id) ON DELETE RESTRICT,
  department_id BIGINT NOT NULL REFERENCES departments(id) ON DELETE RESTRICT,
  shift_id BIGINT NOT NULL REFERENCES shifts(id) ON DELETE RESTRICT,
  work_date DATE NOT NULL, -- Ngày tính công (Ngày bắt đầu ca)
  checkin_at TIMESTAMPTZ,
  checkout_at TIMESTAMPTZ,
  source attendance_source NOT NULL DEFAULT 'online',
  original_source attendance_source NOT NULL DEFAULT 'online', -- Lưu nguồn gốc ban đầu, không bị ghi đè khi admin sửa công
  approval_status approval_status NOT NULL DEFAULT 'approved',
  work_status work_status NOT NULL DEFAULT 'normal',
  late_min INTEGER NOT NULL DEFAULT 0 CHECK (late_min >= 0),
  early_min INTEGER NOT NULL DEFAULT 0 CHECK (early_min >= 0),
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 0.00 CHECK (work_credit >= 0),
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_attendance_employee_shift_date UNIQUE (employee_id, shift_id, work_date)
);

CREATE TRIGGER trg_attendance_records_updated_at BEFORE UPDATE ON attendance_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 18. ATTENDANCE EVIDENCES (Bằng chứng chấm công chi tiết vào/ra)
-- =========================================================
CREATE TABLE attendance_evidences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id BIGINT NOT NULL REFERENCES attendance_records(id) ON DELETE CASCADE,
  punch_type punch_type NOT NULL,
  device_id BIGINT REFERENCES devices(id) ON DELETE SET NULL,
  client_time TIMESTAMPTZ NOT NULL,
  server_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  lat NUMERIC(10,7) CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(10,7) CHECK (lng BETWEEN -180 AND 180),
  accuracy_m NUMERIC(8,2),
  geom geography(Point, 4326),
  wifi_ssid VARCHAR(190),
  wifi_bssid VARCHAR(60),
  photo_path VARCHAR(255),
  note VARCHAR(255),
  gps_valid BOOLEAN NOT NULL DEFAULT FALSE,
  wifi_valid BOOLEAN NOT NULL DEFAULT FALSE,
  distance_m NUMERIC(10,2), -- Khoảng cách thực tế đo được
  matched_location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
  matched_wifi_id BIGINT REFERENCES wifis(id) ON DELETE SET NULL,
  validation_error VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_evidence_content CHECK (
    (lat IS NOT NULL AND lng IS NOT NULL) OR (wifi_ssid IS NOT NULL) OR (photo_path IS NOT NULL)
  )
);

CREATE TRIGGER trg_attendance_evidences_geom BEFORE INSERT OR UPDATE OF lat, lng ON attendance_evidences
FOR EACH ROW EXECUTE FUNCTION set_geography_point();

-- =========================================================
-- 19. ATTENDANCE EDIT LOGS (Nhật ký Admin sửa công)
-- =========================================================
CREATE TABLE attendance_edit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id BIGINT NOT NULL REFERENCES attendance_records(id) ON DELETE CASCADE,
  edited_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  before_json JSONB,
  after_json JSONB NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- 20. NOTIFICATIONS (Thông báo hệ thống)
-- =========================================================
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(190) NOT NULL,
  body TEXT,
  data_json JSONB,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- TỐI ƯU HÓA CHỈ MỤC (INDEXING) - TẬN DỤNG TỐI ĐA BỘ LỌC QUERY
-- =========================================================

-- 1. Index Toàn vẹn & Lọc Soft Delete (Partial Indexes)
CREATE UNIQUE INDEX uq_company_code_active ON companies (code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_employee_company_code_active ON employees (company_id, employee_code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_membership_user_company_active ON company_memberships (user_id, company_id) WHERE deleted_at IS NULL;

-- 2. Index cho Khoá ngoại (Tránh Full Table Scan khi thực hiện JOIN)
CREATE INDEX idx_branches_company_id ON branches(company_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_departments_company_id ON departments(company_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_departments_branch_id ON departments(branch_id) WHERE branch_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_employees_user_id ON employees(user_id) WHERE status = 'active' AND deleted_at IS NULL;
CREATE INDEX idx_company_memberships_employee_id ON company_memberships(employee_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_devices_user_id ON devices(user_id);
CREATE INDEX idx_locations_branch_id ON locations(branch_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_wifis_branch_id ON wifis(branch_id) WHERE deleted_at IS NULL;

-- 3. Composite Indexes - Tối ưu hoá truy vấn Báo cáo & Lịch sử
-- Tối ưu cho query thống kê công của toàn công ty theo khoảng thời gian
CREATE INDEX idx_attendance_records_company_date ON attendance_records(company_id, work_date);
-- Tối ưu cho query thống kê công theo chi nhánh
CREATE INDEX idx_attendance_records_branch_date ON attendance_records(branch_id, work_date);
-- Tối ưu cho query thống kê công theo phòng ban
CREATE INDEX idx_attendance_records_dept_date ON attendance_records(department_id, work_date);
-- Tối ưu cho query chi tiết công của một nhân viên cụ thể theo khoảng thời gian
CREATE INDEX idx_attendance_records_employee_date ON attendance_records(employee_id, work_date);
-- Hỗ trợ tìm kiếm nhanh các bản ghi chấm công cần được duyệt
CREATE INDEX idx_attendance_records_pending_approval ON attendance_records(company_id, approval_status) WHERE approval_status = 'pending';

-- 4. Index Không gian (Spatial Index) - Giúp tìm điểm GPS cực nhanh bằng PostGIS
CREATE INDEX idx_locations_geom ON locations USING GIST(geom) WHERE deleted_at IS NULL;
CREATE INDEX idx_attendance_evidences_geom ON attendance_evidences USING GIST(geom);

-- 5. Index bổ sung cho bảng attendance_evidences
CREATE INDEX idx_attendance_evidences_record_id ON attendance_evidences(attendance_record_id);
CREATE INDEX idx_attendance_evidences_device_id ON attendance_evidences(device_id) WHERE device_id IS NOT NULL;

-- 6. Index cho login_approval_requests
CREATE INDEX idx_login_approval_pending ON login_approval_requests(user_id, status) WHERE status = 'pending';

-- 7. Index cho notifications
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX idx_notifications_company ON notifications(company_id, created_at DESC) WHERE company_id IS NOT NULL;
