-- =========================================================
-- EXTENSIONS (PostgreSQL & PostGIS)
-- =========================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;

-- =========================================================
-- ENUM TYPES
-- =========================================================
CREATE TYPE user_status AS ENUM ('active', 'locked');
CREATE TYPE membership_role AS ENUM ('admin', 'employee');
CREATE TYPE employee_status AS ENUM ('active', 'locked');
CREATE TYPE gender_type AS ENUM ('male', 'female', 'other');
CREATE TYPE device_platform AS ENUM ('ios', 'android');
CREATE TYPE device_status AS ENUM ('pending', 'approved', 'rejected', 'revoked');
CREATE TYPE approval_status AS ENUM ('pending', 'approved', 'rejected');
CREATE TYPE wifi_match_mode AS ENUM ('ssid', 'ssid_bssid');
CREATE TYPE attendance_method AS ENUM ('gps', 'wifi', 'gps_wifi');
CREATE TYPE shift_assignment_scope AS ENUM ('company', 'branch', 'department', 'employee');
CREATE TYPE punch_type AS ENUM ('in', 'out');
CREATE TYPE attendance_source AS ENUM ('online', 'offline', 'admin_edit');
CREATE TYPE work_status AS ENUM ('normal', 'late', 'early', 'late_early', 'forgot', 'absent', 'leave');
CREATE TYPE leave_type AS ENUM ('annual', 'sick', 'unpaid', 'other');

-- =========================================================
-- FUNCTION & TRIGGER ĐỂ TỰ ĐỘNG CẬP NHẬT updated_at
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- FUNCTION & TRIGGER ĐỂ TỰ ĐỘNG ĐỒNG BỘ GEOGRAPHY POINT (POSTGIS)
-- =========================================================
CREATE OR REPLACE FUNCTION set_geography_point()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.lat IS NOT NULL AND NEW.lng IS NOT NULL THEN
    NEW.geom = ST_SetSRID(ST_MakePoint(NEW.lng, NEW.lat), 4326)::geography;
  ELSE
    NEW.geom = NULL;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 1. USERS (Tài khoản Đăng nhập Hệ thống)
-- =========================================================
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(190) UNIQUE,
  pass VARCHAR(255),
  full_name VARCHAR(190) NOT NULL,
  birthday DATE,
  gender gender_type,
  is_hunonic BOOLEAN NOT NULL DEFAULT FALSE,
  status user_status NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 2. COMPANIES (Công ty)
-- =========================================================
CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(190) NOT NULL,
  code VARCHAR(60) NOT NULL,
  timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_companies_updated_at BEFORE UPDATE ON companies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 3. BRANCHES (Chi nhánh)
-- =========================================================
CREATE TABLE branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  address VARCHAR(255),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_branch_company UNIQUE (id, company_id)
);

CREATE TRIGGER trg_branches_updated_at BEFORE UPDATE ON branches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 4. DEPARTMENTS (Phòng ban — thuộc chi nhánh hoặc cấp công ty)
-- =========================================================
CREATE TABLE departments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT,
  name VARCHAR(190) NOT NULL,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_department_company UNIQUE (id, company_id),
  CONSTRAINT fk_department_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 5. EMPLOYEES (Hồ sơ Nhân viên từng Công ty)
-- =========================================================
CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  employee_code VARCHAR(60) NOT NULL,
  full_name VARCHAR(190),
  birthday DATE,
  gender gender_type,
  title VARCHAR(120),
  status employee_status NOT NULL DEFAULT 'active',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_employee_company UNIQUE (id, company_id),
  CONSTRAINT uq_employee_user_company UNIQUE (id, user_id, company_id),
  CONSTRAINT fk_employee_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_employee_department_company FOREIGN KEY (department_id, company_id) REFERENCES departments(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 6. COMPANY MEMBERSHIPS (Quyền của User trong từng Công ty)
-- =========================================================
CREATE TABLE company_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT,
  role membership_role NOT NULL DEFAULT 'employee',
  active_department_id BIGINT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_membership_employee_user_company FOREIGN KEY (employee_id, user_id, company_id) REFERENCES employees(id, user_id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_membership_dept_company FOREIGN KEY (active_department_id, company_id) REFERENCES departments(id, company_id) ON DELETE SET NULL,
  CONSTRAINT chk_membership_employee_required CHECK (role = 'admin' OR employee_id IS NOT NULL)
);

CREATE TRIGGER trg_company_memberships_updated_at BEFORE UPDATE ON company_memberships
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 7. DEVICES (Thiết bị đăng ký chấm công)
-- =========================================================
CREATE TABLE devices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_uid VARCHAR(190) NOT NULL,
  device_name VARCHAR(190),
  platform device_platform NOT NULL,
  os_version VARCHAR(60),
  app_version VARCHAR(60),
  push_token VARCHAR(255),
  status device_status NOT NULL DEFAULT 'pending',
  last_login_at TIMESTAMPTZ,
  ip_address VARCHAR(60),
  user_agent VARCHAR(255),
  reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_user_device UNIQUE (user_id, device_uid)
);

CREATE TRIGGER trg_devices_updated_at BEFORE UPDATE ON devices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 8. TOKENS (Quản lý Phiên đăng nhập & Token xác thực)
-- =========================================================
CREATE TABLE tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id BIGINT,
  token VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  ip_address VARCHAR(60),
  user_agent VARCHAR(255),
  active_company_id BIGINT,
  active_employee_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_token_employee_company FOREIGN KEY (active_employee_id, user_id, active_company_id) REFERENCES employees(id, user_id, company_id) ON DELETE SET NULL
);

CREATE TRIGGER trg_tokens_updated_at BEFORE UPDATE ON tokens
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 9. LOCATIONS (Danh mục Vị trí GPS Văn phòng)
-- =========================================================
CREATE TABLE locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL,
  name VARCHAR(190) NOT NULL,
  address VARCHAR(255),
  lat NUMERIC(10,7) NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(10,7) NOT NULL CHECK (lng BETWEEN -180 AND 180),
  radius_m INTEGER NOT NULL DEFAULT 80 CHECK (radius_m > 0),
  geom geography(Point, 4326),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_location_company UNIQUE (id, company_id),
  CONSTRAINT fk_location_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_locations_updated_at BEFORE UPDATE ON locations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_locations_geom BEFORE INSERT OR UPDATE OF lat, lng ON locations
FOR EACH ROW EXECUTE FUNCTION set_geography_point();

-- =========================================================
-- 10. WIFIS (Danh mục Wifi được phép chấm công)
-- =========================================================
CREATE TABLE wifis (
  id 
   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL,
  name VARCHAR(190),
  ssid VARCHAR(190) NOT NULL,
  bssid VARCHAR(60),
  match_mode wifi_match_mode NOT NULL DEFAULT 'ssid_bssid',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_wifi_company UNIQUE (id, company_id),
  CONSTRAINT fk_wifi_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT chk_wifi_bssid_required CHECK (match_mode = 'ssid' OR bssid IS NOT NULL)
);

CREATE TRIGGER trg_wifis_updated_at BEFORE UPDATE ON wifis
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 11. HOLIDAYS (Danh mục Ngày lễ được hưởng lương/công)
-- =========================================================
CREATE TABLE holidays (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  holiday_date DATE NOT NULL,
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 1.00 CHECK (work_credit >= 0), -- Hệ số công ngày lễ (VD: 1.00 công)
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_holiday_company_date UNIQUE (company_id, holiday_date)
);

-- =========================================================
-- 12. SHIFTS (Cấu hình Ca làm)
-- =========================================================
CREATE TABLE shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name VARCHAR(190) NOT NULL,
  start_time INTERVAL NOT NULL,
  end_time INTERVAL NOT NULL,
  checkin_from INTERVAL NOT NULL,
  checkin_to INTERVAL NOT NULL,
  checkout_from INTERVAL NOT NULL,
  checkout_to INTERVAL NOT NULL,
  weekdays SMALLINT NOT NULL CHECK (weekdays BETWEEN 1 AND 127),
  attendance_method attendance_method NOT NULL,
  late_threshold_min INTEGER NOT NULL DEFAULT 0 CHECK (late_threshold_min >= 0),
  early_threshold_min INTEGER NOT NULL DEFAULT 0 CHECK (early_threshold_min >= 0),
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 1.00 CHECK (work_credit >= 0),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_shift_company UNIQUE (id, company_id)
);

CREATE TRIGGER trg_shifts_updated_at BEFORE UPDATE ON shifts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 13. SHIFT ASSIGNMENTS (Gán ca cho Nhân viên/Phòng ban/Chi nhánh)
-- =========================================================
CREATE TABLE shift_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id BIGINT NOT NULL,
  scope_type shift_assignment_scope NOT NULL,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id BIGINT,
  department_id BIGINT,
  employee_id BIGINT,
  starts_on DATE,
  ends_on DATE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_shift_assign_shift_company FOREIGN KEY (shift_id, company_id) REFERENCES shifts(id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_assign_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_assign_dept_company FOREIGN KEY (department_id, company_id) REFERENCES departments(id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_assign_employee_company FOREIGN KEY (employee_id, company_id) REFERENCES employees(id, company_id) ON DELETE CASCADE,
  CONSTRAINT chk_shift_assignment_scope CHECK (
    (scope_type = 'company'    AND branch_id IS NULL AND department_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 'branch'     AND branch_id IS NOT NULL AND department_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 'department' AND department_id IS NOT NULL AND branch_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 'employee'   AND employee_id IS NOT NULL AND branch_id IS NULL AND department_id IS NULL)
  ),
  CONSTRAINT chk_shift_assignment_date_range CHECK (
    ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on
  )
);

CREATE TRIGGER trg_shift_assignments_updated_at BEFORE UPDATE ON shift_assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 14. LEAVE REQUESTS (Đơn xin nghỉ phép của Nhân viên)
-- =========================================================
CREATE TABLE leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT NOT NULL,
  leave_type leave_type NOT NULL,
  starts_on DATE NOT NULL,
  ends_on DATE NOT NULL,
  reason VARCHAR(255),
  status approval_status NOT NULL DEFAULT 'pending',
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_leave_employee_company FOREIGN KEY (employee_id, company_id) REFERENCES employees(id, company_id) ON DELETE CASCADE,
  CONSTRAINT chk_leave_date_range CHECK (ends_on >= starts_on)
);

CREATE TRIGGER trg_leave_requests_updated_at BEFORE UPDATE ON leave_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 15. ATTENDANCE RECORDS (Bảng ghi công tổng hợp theo ngày-nhân viên-ca)
-- =========================================================
CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT NOT NULL,
  branch_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  shift_id BIGINT NOT NULL,
  work_date DATE NOT NULL,
  checkin_at TIMESTAMPTZ,
  checkout_at TIMESTAMPTZ,
  source attendance_source NOT NULL DEFAULT 'online',
  original_source attendance_source NOT NULL DEFAULT 'online',
  approval_status approval_status NOT NULL DEFAULT 'approved',
  work_status work_status NOT NULL DEFAULT 'normal',
  late_min INTEGER NOT NULL DEFAULT 0 CHECK (late_min >= 0),
  early_min INTEGER NOT NULL DEFAULT 0 CHECK (early_min >= 0),
  actual_work_minutes INTEGER NOT NULL DEFAULT 0 CHECK (actual_work_minutes >= 0),
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 0.00 CHECK (work_credit >= 0),
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_attendance_record_employee UNIQUE (id, employee_id),
  CONSTRAINT uq_attendance_employee_shift_date UNIQUE (employee_id, shift_id, work_date),
  CONSTRAINT fk_attendance_employee_company FOREIGN KEY (employee_id, company_id) REFERENCES employees(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_dept_company FOREIGN KEY (department_id, company_id) REFERENCES departments(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_shift_company FOREIGN KEY (shift_id, company_id) REFERENCES shifts(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_attendance_records_updated_at BEFORE UPDATE ON attendance_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 16. ATTENDANCE EVIDENCES (Bằng chứng chấm công chi tiết vào/ra)
-- =========================================================
CREATE TABLE attendance_evidences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  attendance_record_id BIGINT,
  punch_type punch_type NOT NULL,
  device_id BIGINT REFERENCES devices(id) ON DELETE SET NULL,
  client_time TIMESTAMPTZ NOT NULL,
  server_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  lat NUMERIC(10,7) CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(10,7) CHECK (lng BETWEEN -180 AND 180),
  accuracy_m NUMERIC(8,2),
  geom geography(Point, 4326),
  wifi_ssid VARCHAR(190),
  wifi_bssid VARCHAR(60),
  photo VARCHAR(255),
  note VARCHAR(255),
  gps_valid BOOLEAN NOT NULL DEFAULT FALSE,
  wifi_valid BOOLEAN NOT NULL DEFAULT FALSE,
  distance_m NUMERIC(10,2),
  matched_location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,
  matched_wifi_id BIGINT REFERENCES wifis(id) ON DELETE SET NULL,
  validation_error VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_evidence_record_employee FOREIGN KEY (attendance_record_id, employee_id) REFERENCES attendance_records(id, employee_id) ON DELETE CASCADE,
  CONSTRAINT chk_evidence_content CHECK (
    (lat IS NOT NULL AND lng IS NOT NULL) OR (wifi_ssid IS NOT NULL) OR (photo IS NOT NULL)
  )
);

CREATE TRIGGER trg_attendance_evidences_geom BEFORE INSERT OR UPDATE OF lat, lng ON attendance_evidences
FOR EACH ROW EXECUTE FUNCTION set_geography_point();

-- =========================================================
-- 17. ATTENDANCE EDIT LOGS (Nhật ký Admin sửa công)
-- =========================================================
CREATE TABLE attendance_edit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id BIGINT NOT NULL REFERENCES attendance_records(id) ON DELETE CASCADE,
  edited_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  before_json JSONB,
  after_json JSONB NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- 18. NOTIFICATIONS (Thông báo hệ thống)
-- =========================================================
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(190) NOT NULL,
  body TEXT,
  data_json JSONB,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- TỐI ƯU HÓA CHỈ MỤC (INDEXING) - TẬN DỤNG TỐI ĐA BỘ LỌC QUERY
-- =========================================================

-- 1. Index Toàn vẹn & Lọc Delete (Partial Indexes)
CREATE UNIQUE INDEX uq_company_code_active ON companies (code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_employee_company_code_active ON employees (company_id, employee_code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_membership_user_company_active ON company_memberships (user_id, company_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_employee_user_company_active ON employees (user_id, company_id) WHERE deleted_at IS NULL;

-- 2. Index cho Khoá ngoại
CREATE INDEX idx_branches_company_id ON branches(company_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_departments_company_id ON departments(company_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_departments_branch_id ON departments(branch_id) WHERE branch_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_employees_user_id ON employees(user_id) WHERE status = 'active' AND deleted_at IS NULL;
CREATE INDEX idx_company_memberships_employee_id ON company_memberships(employee_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_devices_user_id ON devices(user_id);
CREATE INDEX idx_locations_branch_id ON locations(branch_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_wifis_branch_id ON wifis(branch_id) WHERE deleted_at IS NULL;

-- Đảm bảo mỗi user chỉ có tối đa 1 thiết bị ở trạng thái "approved" tại một thời điểm
CREATE UNIQUE INDEX uq_user_active_device ON devices (user_id) WHERE status = 'approved';

-- Index cho phân vùng gán ca không dùng unique index cũ
CREATE INDEX idx_shift_assign_company ON shift_assignments(company_id) WHERE scope_type = 'company' AND deleted_at IS NULL;
CREATE INDEX idx_shift_assign_branch ON shift_assignments(branch_id) WHERE scope_type = 'branch' AND deleted_at IS NULL;
CREATE INDEX idx_shift_assign_department ON shift_assignments(department_id) WHERE scope_type = 'department' AND deleted_at IS NULL;
CREATE INDEX idx_shift_assign_employee ON shift_assignments(employee_id) WHERE scope_type = 'employee' AND deleted_at IS NULL;

-- Index cho leave_requests
CREATE INDEX idx_leave_requests_employee ON leave_requests(employee_id, starts_on);
CREATE INDEX idx_leave_requests_pending ON leave_requests(company_id, status) WHERE status = 'pending';

-- Index cho holidays
CREATE INDEX idx_holidays_company ON holidays(company_id, holiday_date);

-- 3. Composite Indexes - Tối ưu hoá truy vấn Báo cáo & Lịch sử
CREATE INDEX idx_attendance_records_company_date ON attendance_records(company_id, work_date);
CREATE INDEX idx_attendance_records_branch_date ON attendance_records(branch_id, work_date);
CREATE INDEX idx_attendance_records_dept_date ON attendance_records(department_id, work_date);
CREATE INDEX idx_attendance_records_employee_date ON attendance_records(employee_id, work_date);
CREATE INDEX idx_attendance_records_pending_approval ON attendance_records(company_id, approval_status) WHERE approval_status = 'pending';

-- 4. Index Không gian (Spatial Index) - Giúp tìm điểm GPS cực nhanh bằng PostGIS
CREATE INDEX idx_locations_geom ON locations USING GIST(geom) WHERE deleted_at IS NULL;
CREATE INDEX idx_attendance_evidences_geom ON attendance_evidences USING GIST(geom);

-- 5. Index bổ sung cho bảng attendance_evidences
CREATE INDEX idx_attendance_evidences_record_id ON attendance_evidences(attendance_record_id);
CREATE INDEX idx_attendance_evidences_device_id ON attendance_evidences(device_id) WHERE device_id IS NOT NULL;
CREATE INDEX idx_attendance_evidences_employee_id ON attendance_evidences(employee_id);

-- 6. Index cho notifications
CREATE INDEX idx_notifications_user_unread ON notifications(user_id, created_at DESC) WHERE read_at IS NULL;
CREATE INDEX idx_notifications_company ON notifications(company_id, created_at DESC) WHERE company_id IS NOT NULL;
