-- =========================================================
-- EXTENSIONS (PostgreSQL)
-- =========================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================
-- FUNCTION & TRIGGER ĐỂ TỰ ĐỘNG CẬP NHẬT updated_at
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 1. USERS (Tài khoản Đăng nhập Hệ thống)
-- =========================================================
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(190) UNIQUE,
  pass VARCHAR(255),
  full_name TEXT NOT NULL,
  birthday DATE,
  gender SMALLINT CHECK (gender IN (1, 2, 3)),
  is_hunonic BOOLEAN NOT NULL DEFAULT FALSE,
  status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 2. COMPANIES (Công ty)
-- =========================================================
CREATE TABLE companies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code VARCHAR(60) NOT NULL,
  timezone VARCHAR(60) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_companies_updated_at BEFORE UPDATE ON companies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 3. BRANCHES (Chi nhánh)
-- =========================================================
CREATE TABLE branches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  address TEXT,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_branch_company UNIQUE (id, company_id)
);

CREATE TRIGGER trg_branches_updated_at BEFORE UPDATE ON branches
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 4. DEPARTMENTS (Phòng ban — thuộc chi nhánh hoặc cấp công ty)
-- =========================================================
CREATE TABLE departments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id INTEGER,
  name TEXT NOT NULL,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_department_company UNIQUE (id, company_id),
  CONSTRAINT fk_department_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_departments_updated_at BEFORE UPDATE ON departments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 5. EMPLOYEES (Hồ sơ Nhân viên từng Công ty)
-- =========================================================
CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id INTEGER NOT NULL,
  department_id INTEGER NOT NULL,
  employee_code VARCHAR(60) NOT NULL,
  title VARCHAR(120),
  status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (1, 2)),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_employee_company UNIQUE (id, company_id),
  CONSTRAINT uq_employee_user_company UNIQUE (id, user_id, company_id),
  CONSTRAINT fk_employee_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_employee_department_company FOREIGN KEY (department_id, company_id) REFERENCES departments(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_employees_updated_at BEFORE UPDATE ON employees
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 6. COMPANY MEMBERSHIPS (Quyền của User trong từng Công ty)
-- =========================================================
CREATE TABLE company_memberships (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT,
  role SMALLINT NOT NULL DEFAULT 2 CHECK (role IN (1, 2)),
  active_department_id INTEGER,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_membership_employee_user_company FOREIGN KEY (employee_id, user_id, company_id) REFERENCES employees(id, user_id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_membership_dept_company FOREIGN KEY (active_department_id, company_id) REFERENCES departments(id, company_id) ON DELETE SET NULL,
  CONSTRAINT chk_membership_employee_required CHECK (role = 1 OR employee_id IS NOT NULL)
);

CREATE TRIGGER trg_company_memberships_updated_at BEFORE UPDATE ON company_memberships
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 7. DEVICES (Thiết bị đăng ký chấm công)
-- =========================================================
CREATE TABLE devices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_uid TEXT NOT NULL,
  device_name TEXT,
  platform SMALLINT NOT NULL CHECK (platform IN (1, 2)),
  os_version VARCHAR(60),
  app_version VARCHAR(60),
  push_token VARCHAR(255),
  status SMALLINT NOT NULL DEFAULT 1 CHECK (status IN (1, 2, 3, 4)),
  last_login_at TIMESTAMPTZ,
  ip_address VARCHAR(60),
  user_agent VARCHAR(255),
  reviewed_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_user_device UNIQUE (user_id, device_uid)
);

CREATE TRIGGER trg_devices_updated_at BEFORE UPDATE ON devices
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 8. TOKENS (Quản lý Phiên đăng nhập & Token xác thực)
-- =========================================================
CREATE TABLE tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id INTEGER,
  token VARCHAR(255) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  ip_address VARCHAR(60),
  user_agent VARCHAR(255),
  active_company_id INTEGER,
  active_employee_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_token_employee_company FOREIGN KEY (active_employee_id, user_id, active_company_id) REFERENCES employees(id, user_id, company_id) ON DELETE SET NULL
);

CREATE TRIGGER trg_tokens_updated_at BEFORE UPDATE ON tokens
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 9. LOCATIONS (Danh mục Vị trí GPS Văn phòng)
-- =========================================================
CREATE TABLE locations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id INTEGER NOT NULL,
  employee_id BIGINT REFERENCES employees(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  address TEXT,
  lat NUMERIC(10,7) NOT NULL CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(10,7) NOT NULL CHECK (lng BETWEEN -180 AND 180),
  radius_m INTEGER NOT NULL DEFAULT 80 CHECK (radius_m > 0),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_location_company UNIQUE (id, company_id),
  CONSTRAINT fk_location_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_locations_updated_at BEFORE UPDATE ON locations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 10. WIFIS (Danh mục Wifi được phép chấm công)
-- =========================================================
CREATE TABLE wifis (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id INTEGER NOT NULL,
  name TEXT,
  ssid VARCHAR(190) NOT NULL,
  bssid VARCHAR(60),
  match_mode SMALLINT NOT NULL DEFAULT 2 CHECK (match_mode IN (1, 2)),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_wifi_company UNIQUE (id, company_id),
  CONSTRAINT fk_wifi_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT chk_wifi_bssid_required CHECK (match_mode = 1 OR bssid IS NOT NULL)
);

CREATE TRIGGER trg_wifis_updated_at BEFORE UPDATE ON wifis
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 12. SHIFTS (Cấu hình Ca làm)
-- =========================================================
CREATE TABLE shifts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  start_time INTERVAL NOT NULL,
  end_time INTERVAL NOT NULL,
  checkin_from INTERVAL NOT NULL,
  checkin_to INTERVAL NOT NULL,
  checkout_from INTERVAL NOT NULL,
  checkout_to INTERVAL NOT NULL,
  weekdays SMALLINT NOT NULL CHECK (weekdays BETWEEN 1 AND 127),
  attendance_method SMALLINT NOT NULL CHECK (attendance_method IN (1, 2, 3, 4)),
  late_threshold_min INTEGER NOT NULL DEFAULT 0 CHECK (late_threshold_min >= 0),
  early_threshold_min INTEGER NOT NULL DEFAULT 0 CHECK (early_threshold_min >= 0),
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 1.00 CHECK (work_credit >= 0),
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_shift_company UNIQUE (id, company_id)
);

CREATE TRIGGER trg_shifts_updated_at BEFORE UPDATE ON shifts
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 13. SHIFT ASSIGNMENTS (Gán ca cho Nhân viên/Phòng ban/Chi nhánh)
-- =========================================================
CREATE TABLE shift_assignments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_id INTEGER NOT NULL,
  scope_type SMALLINT NOT NULL CHECK (scope_type IN (1, 2, 3, 4)),
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  branch_id INTEGER,
  department_id INTEGER,
  employee_id BIGINT,
  starts_on DATE,
  ends_on DATE,
  deleted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_shift_assign_shift_company FOREIGN KEY (shift_id, company_id) REFERENCES shifts(id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_assign_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_assign_dept_company FOREIGN KEY (department_id, company_id) REFERENCES departments(id, company_id) ON DELETE CASCADE,
  CONSTRAINT fk_shift_assign_employee_company FOREIGN KEY (employee_id, company_id) REFERENCES employees(id, company_id) ON DELETE CASCADE,
  CONSTRAINT chk_shift_assignment_scope CHECK (
    (scope_type = 1 AND branch_id IS NULL AND department_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 2 AND branch_id IS NOT NULL AND department_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 3 AND department_id IS NOT NULL AND branch_id IS NULL AND employee_id IS NULL)
    OR
    (scope_type = 4 AND employee_id IS NOT NULL AND branch_id IS NULL AND department_id IS NULL)
  ),
  CONSTRAINT chk_shift_assignment_date_range CHECK (
    ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on
  )
);

CREATE TRIGGER trg_shift_assignments_updated_at BEFORE UPDATE ON shift_assignments
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 15. ATTENDANCE RECORDS (Bảng ghi công tổng hợp theo ngày-nhân viên-ca)
-- =========================================================
CREATE TABLE attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE RESTRICT,
  employee_id BIGINT NOT NULL,
  branch_id INTEGER NOT NULL,
  department_id INTEGER NOT NULL,
  shift_id INTEGER NOT NULL,
  work_date DATE NOT NULL,
  checkin_at TIMESTAMPTZ,
  checkout_at TIMESTAMPTZ,
  source SMALLINT NOT NULL DEFAULT 1 CHECK (source IN (1, 2, 3)),
  original_source SMALLINT NOT NULL DEFAULT 1 CHECK (original_source IN (1, 2, 3)),
  approval_status SMALLINT NOT NULL DEFAULT 2 CHECK (approval_status IN (1, 2, 3)),
  work_status SMALLINT NOT NULL DEFAULT 1 CHECK (work_status IN (1, 2, 3, 4, 5, 6, 7)),
  late_min INTEGER NOT NULL DEFAULT 0 CHECK (late_min >= 0),
  early_min INTEGER NOT NULL DEFAULT 0 CHECK (early_min >= 0),
  actual_work_minutes INTEGER NOT NULL DEFAULT 0 CHECK (actual_work_minutes >= 0),
  work_credit NUMERIC(4,2) NOT NULL DEFAULT 0.00 CHECK (work_credit >= 0),
  approved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  rejection_reason VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_attendance_record_employee UNIQUE (id, employee_id),
  CONSTRAINT uq_attendance_employee_shift_date UNIQUE (employee_id, shift_id, work_date),
  CONSTRAINT fk_attendance_employee_company FOREIGN KEY (employee_id, company_id) REFERENCES employees(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_branch_company FOREIGN KEY (branch_id, company_id) REFERENCES branches(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_dept_company FOREIGN KEY (department_id, company_id) REFERENCES departments(id, company_id) ON DELETE RESTRICT,
  CONSTRAINT fk_attendance_shift_company FOREIGN KEY (shift_id, company_id) REFERENCES shifts(id, company_id) ON DELETE RESTRICT
);

CREATE TRIGGER trg_attendance_records_updated_at BEFORE UPDATE ON attendance_records
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- =========================================================
-- 16. ATTENDANCE EVIDENCES (Bằng chứng chấm công chi tiết vào/ra)
-- =========================================================
CREATE TABLE attendance_evidences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  attendance_record_id BIGINT,
  punch_type SMALLINT NOT NULL CHECK (punch_type IN (1, 2)),
  device_id INTEGER REFERENCES devices(id) ON DELETE SET NULL,
  client_time TIMESTAMPTZ NOT NULL,
  server_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  lat NUMERIC(10,7) CHECK (lat BETWEEN -90 AND 90),
  lng NUMERIC(10,7) CHECK (lng BETWEEN -180 AND 180),
  accuracy_m NUMERIC(8,2),
  wifi_ssid VARCHAR(190),
  wifi_bssid VARCHAR(60),
  photo VARCHAR(255),
  note VARCHAR(255),
  gps_valid BOOLEAN NOT NULL DEFAULT FALSE,
  wifi_valid BOOLEAN NOT NULL DEFAULT FALSE,
  distance_m NUMERIC(10,2),
  matched_location_id INTEGER REFERENCES locations(id) ON DELETE SET NULL,
  matched_wifi_id INTEGER REFERENCES wifis(id) ON DELETE SET NULL,
  validation_error VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_evidence_record_employee FOREIGN KEY (attendance_record_id, employee_id) REFERENCES attendance_records(id, employee_id) ON DELETE CASCADE,
  CONSTRAINT chk_evidence_content CHECK (
    (lat IS NOT NULL AND lng IS NOT NULL) OR (wifi_ssid IS NOT NULL) OR (photo IS NOT NULL)
  )
);

-- =========================================================
-- 17. ATTENDANCE EDIT LOGS (Nhật ký Admin sửa công)
-- =========================================================
CREATE TABLE attendance_edit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_record_id BIGINT NOT NULL REFERENCES attendance_records(id) ON DELETE CASCADE,
  edited_by BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  before_json JSONB,
  after_json JSONB NOT NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- TỐI ƯU HÓA CHỈ MỤC (INDEXING)
-- =========================================================

-- 1. Index Toàn vẹn & Lọc Delete (Partial Indexes)
CREATE UNIQUE INDEX uq_company_code_active ON companies (code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_employee_company_code_active ON employees (company_id, employee_code) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_membership_user_company_active ON company_memberships (user_id, company_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_employee_user_company_active ON employees (user_id, company_id) WHERE deleted_at IS NULL;

-- 2. Index cho Khoá ngoại
CREATE INDEX idx_branches_company_id ON branches(company_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_departments_company_id ON departments(company_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_departments_branch_id ON departments(branch_id) WHERE branch_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_employees_user_id ON employees(user_id) WHERE status = 1 AND deleted_at IS NULL;
CREATE INDEX idx_company_memberships_employee_id ON company_memberships(employee_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_devices_user_id ON devices(user_id);
CREATE INDEX idx_locations_branch_id ON locations(branch_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_wifis_branch_id ON wifis(branch_id) WHERE deleted_at IS NULL;

-- Đảm bảo mỗi user chỉ có tối đa 1 thiết bị được duyệt tại một thời điểm
CREATE UNIQUE INDEX uq_user_active_device ON devices (user_id) WHERE status = 2;

-- Index cho phân vùng gán ca
CREATE INDEX idx_shift_assign_company ON shift_assignments(company_id) WHERE scope_type = 1 AND deleted_at IS NULL;
CREATE INDEX idx_shift_assign_branch ON shift_assignments(branch_id) WHERE scope_type = 2 AND deleted_at IS NULL;
CREATE INDEX idx_shift_assign_department ON shift_assignments(department_id) WHERE scope_type = 3 AND deleted_at IS NULL;
CREATE INDEX idx_shift_assign_employee ON shift_assignments(employee_id) WHERE scope_type = 4 AND deleted_at IS NULL;

-- 3. Composite Indexes - Tối ưu hoá truy vấn Báo cáo & Lịch sử
CREATE INDEX idx_attendance_records_company_date ON attendance_records(company_id, work_date);
CREATE INDEX idx_attendance_records_branch_date ON attendance_records(branch_id, work_date);
CREATE INDEX idx_attendance_records_dept_date ON attendance_records(department_id, work_date);
CREATE INDEX idx_attendance_records_employee_date ON attendance_records(employee_id, work_date);
CREATE INDEX idx_attendance_records_pending_approval ON attendance_records(company_id, approval_status) WHERE approval_status = 1;



-- 5. Index bổ sung cho bảng attendance_evidences
CREATE INDEX idx_attendance_evidences_record_id ON attendance_evidences(attendance_record_id);
CREATE INDEX idx_attendance_evidences_device_id ON attendance_evidences(device_id) WHERE device_id IS NOT NULL;
CREATE INDEX idx_attendance_evidences_employee_id ON attendance_evidences(employee_id);
